[build]
  command = "npm run test && npm run build"
  functions = "functions/"
  publish = "frontend/out/"

[context.develop.environment]
  API_HOST = "https://develop--voice-list.netlify.app"

[context.production.environment]
  API_HOST = "https://voice-list.netlify.app"

[context.deploy-preview]
  API_HOST = DEPLOY_PRIME_URL