[build]
  command = "npm run build"
  functions = "functions/"
  publish = "public/"

[dev]
  publish = "public/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/graphql-api"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
